---
title: "Spatial_analysis on airport vehicles"
author: "Zhongjia Wei"
date: "11/30/2018"
output: html_document
---
##Importing libraries
```{r}
library(sp, lib.loc="E:/R/R-3.5.1/library")  

library(raster, lib.loc="E:/R/R-3.5.1/library")

library(rgdal, lib.loc="E:/R/R-3.5.1/library")
```


##Loading data
```{r}
dir<-"D:/data/grouproject"
air_vehicles_csv<-file.path(dir,"airport.csv")
airport_shp<-file.path(dir,"t1t2.shp")
air_vehicles<-read.csv(air_vehicles_csv, header = TRUE, sep = ",")
boundary1<-readOGR(airport_shp)
```

##Wordcloud
```{r}
#subseting data
write.table(air_vehicles[,11], file = "cartype.txt", quote = FALSE,
            row.names = FALSE)
#importing libraries
library(twitteR, lib.loc="E:/R/R-3.5.1/library")
library(tm, lib.loc="E:/R/R-3.5.1/library")
library(wordcloud, lib.loc="E:/R/R-3.5.1/library")
library(RColorBrewer, lib.loc="E:/R/R-3.5.1/library")

my_corpus = Corpus(DirSource(dir))

tdm = TermDocumentMatrix(my_corpus,
control = list(removePunctuation = TRUE,stopwords = c("yes", stopwords("english")),
removeNumbers = TRUE, tolower = TRUE))
# define tdm as a matrix
m = as.matrix(tdm)
# get word counts in decreasing order
word_freqs = sort(rowSums(m), decreasing=TRUE)
# create a data frame with words and their frequencies
dm1 = data.frame(word=names(word_freqs), freq=word_freqs)
#only choose the 100 most frequent words
dm = head(dm1,100)
```


```{r, message=FALSE}
# plot wordcloud in R
wordcloud(dm$word, dm$freq, random.order=FALSE, random.color=FALSE, rot.per=
0, colors=brewer.pal(8, "Dark2"))
png("WordCloud.png", width=12, height=8, units="in", res=300)
wordcloud(dm$word, dm$freq, random.order=FALSE, random.color=FALSE, rot.per=
0, colors=brewer.pal(8, "Dark2"))
# dev.off will save the output PNG file into the working folder
dev.off()
```


```{r}
coords <- air_vehicles[ , c("X", "Y")]   # coordinates
data   <- air_vehicles[ , 2:7]          # data
crs    <- CRS("+init=epsg:4326")
d<- SpatialPointsDataFrame(coords = coords,
                               data = data, 
                               proj4string = crs)
CRS.new <- CRS("+proj=lcc +lat_1=32.78333333333333 +lat_2=33.88333333333333 +lat_0=32.16666666666666 +lon_0=-116.25
+x_0=2000000 +y_0=500000.0000000001 +datum=NAD83 +units=us-ft +no_defs +ellps=GRS80 +towgs84=0,0,0 ")
d.proj <- spTransform(d, CRS.new)
coords_proj <- coordinates(d.proj)
coords_d <- coordinates(d)
```


##Plot all the points
```{r}
plot(boundary1,col="gray",border="black")

plot(d,pch='*',col='red',cex=.5,add=TRUE)
```



##Density map of all points
```{r, message=FALSE}
library(spatstat, lib.loc="E:/R/R-3.5.1/library")
pnt1=ppp(d$X,d$Y,c(min(d$X),-117.17),
       c(min(d$Y),max(d$Y)))
plot(density(pnt1),0.01)
plot(d,pch='*',col='red',cex=.5,add=TRUE)

```
##DBscan clustering
```{r}
library("dbscan", lib.loc="E:/R/R-3.5.1/library")

#only subset 15000 points inorder to ensure the best clustering results
d1<-head(coords_proj,15000)

res <- dbscan(d1, eps =10, minPts = 15)
res
```
```{r}
airvehicles<-head(air_vehicles,15000)
#Only subset the first 3 clusters
cluster1<-airvehicles[res$cluster %in% 1,]
cluster2<-airvehicles[res$cluster %in% 2,]
cluster3<-airvehicles[res$cluster %in% 3,]

coords_cluster1 <- cluster1[ , c("X", "Y")] 
data_cluster1   <- cluster1[ , 2:7]  
coords_cluster2 <- cluster2[ , c("X", "Y")] 
data_cluster2   <- cluster2[ , 2:7]  
coords_cluster3 <- cluster3[ , c("X", "Y")] 
data_cluster3   <- cluster3[ , 2:7]  

crs    <- CRS("+init=epsg:4326")
d_cluster1<- SpatialPointsDataFrame(coords = coords_cluster1,
                               data = data_cluster1, 
                               proj4string = crs)
d_cluster2<- SpatialPointsDataFrame(coords = coords_cluster2,
                               data = data_cluster2, 
                               proj4string = crs)
d_cluster3<- SpatialPointsDataFrame(coords = coords_cluster3,
                               data = data_cluster3, 
                               proj4string = crs)

plot(boundary1,col="gray",border="black")

#terminal1
plot(d_cluster1,col="red",add=TRUE)
#terminal2
plot(d_cluster2,col="green",add=TRUE)
#economy shuttle stop 9
plot(d_cluster3,col="blue",add=TRUE)
```
##calculate the average time vehicles spent in different pickup/dropoff places 
```{r}
data_cluster1$time_interval<-as.numeric(difftime(strptime(data_cluster1$Time.of.exit,"%H:%M"),strptime(data_cluster1$Time.of.entry,"%H:%M")))
data_cluster1$time_interval[data_cluster1$time_interval<0]<-1440+data_cluster1$time_interval[data_cluster1$time_interval<0]

data_cluster2$time_interval<-as.numeric(difftime(strptime(data_cluster2$Time.of.exit,"%H:%M"),strptime(data_cluster2$Time.of.entry,"%H:%M")))
data_cluster2$time_interval[data_cluster2$time_interval<0]<-1440+data_cluster2$time_interval[data_cluster2$time_interval<0]

data_cluster3$time_interval<-as.numeric(difftime(strptime(data_cluster3$Time.of.exit,"%H:%M"),strptime(data_cluster3$Time.of.entry,"%H:%M")))
data_cluster3$time_interval[data_cluster3$time_interval<0]<-1440+data_cluster3$time_interval[data_cluster3$time_interval<0]
 
mean(data_cluster1$time_interval)
mean(data_cluster2$time_interval)
mean(data_cluster3$time_interval)
```

##Showing the distribution of time in 3 clusters
```{r}
par(mfrow=c(2,2))
hist(data_cluster1$time_interval,main="terminal1")
hist(data_cluster2$time_interval,main="terminal2")
hist(data_cluster3$time_interval,main="economy shuttle stop 9")
```